name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build and push Docker image
        uses: google-github-actions/build-and-push-docker-image@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/django-app
          tag: latest
          dockerfile: Dockerfile
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@master
        with:
          service: django-app
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/django-app:latest
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: us-central1
          platform: managed
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          allow_unauthenticated: true
