name: CI/CD for orders

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_SECRET: ${{ secrets.SECRET }} # Replace with your secrets
          envkey_AT_USERNAME: ${{ secrets.AT_USERNAME }} # Replace with your secrets
          envkey_AT_API_KEY: ${{ secrets.AT_API_KEY }} # Replace with your secrets
          path: .env # Path to your .env file

      - name: Run Tests
        run: |
          python manage.py test
